package com.jukes.extension;

import com.jukes.config.TestConfig;
import com.jukes.model.jukes.Component;
import com.jukes.model.jukes.Juke;
import com.jukes.model.settings.Setting;
import com.jukes.model.settings.Settings;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.assertj.core.util.Lists;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.Arrays;
import java.util.List;

public class TestExtension extends TestConfig {

    @SneakyThrows
    public Mono<Settings> getSettings() {
        Mono<Settings> settingsMono = Mono.just(
                Settings.builder().settings(Arrays.asList(
                        Setting.builder()
                                .id("e9869bbe-887f-4d0a-bb9d-b81eb55fbf0a")
                                .requires(Arrays.asList("camera", "speaker", "pcb"))
                                .build(),
                        Setting.builder()
                                .id("db886f37-16e3-4a55-80e4-cfffc9e4e464")
                                .requires(Arrays.asList(
                                        "touchscreen",
                                        "money_pcb",
                                        "led_panel",
                                        "money_receiver"
                                ))
                                .build(),
                        Setting.builder()
                                .id("2321763c-8e06-4a31-873d-0b5dac2436da")
                                .requires(Arrays.asList(
                                        "touchscreen",
                                        "money_pcb"
                                ))
                                .build(),
                        Setting.builder()
                                .id("2f58dbd4-47cb-4eef-bb72-623f4aa4fe5d")
                                .requires(Arrays.asList(
                                        "money_pcb",
                                        "money_receiver",
                                        "speaker",
                                        "led_panel",
                                        "money_receiver"
                                ))
                                .build(),
                        Setting.builder()
                                .id("b43f247a-8478-4f24-8e28-792fcfe539f5")
                                .requires(Arrays.asList(
                                        "camera",
                                        "amplifier"
                                ))
                                .build(),
                        Setting.builder()
                                .id("86506865-f971-496e-9b90-75994f251459")
                                .requires(Lists.newArrayList())
                                .build(),
                        Setting.builder()
                                .id("3a6423cf-f226-4cb1-bf51-2954bc0941d1")
                                .requires(Arrays.asList(
                                        "speaker",
                                        "money_receiver"
                                ))
                                .build(),
                        Setting.builder()
                                .id("fda6c028-ca52-418c-ac91-574228c171c5")
                                .requires(Arrays.asList(
                                        "money_storage",
                                        "speaker",
                                        "money_storage"
                                ))
                                .build(),
                        Setting.builder()
                                .id("515ef38b-0529-418f-a93a-7f2347fc5805")
                                .requires(List.of(
                                        "money_storage"
                                ))
                                .build(),
                        Setting.builder()
                                .id("1b9ad45f-8c0e-4993-b980-377ac19b121e")
                                .requires(Arrays.asList(
                                        "amplifier",
                                        "pcb",
                                        "money_receiver",
                                        "money_storage"
                                ))
                                .build(),
                        Setting.builder()
                                .id("bd9df656-323c-4417-b14b-bd9e9743be23")
                                .requires(Arrays.asList(
                                        "money_pcb",
                                        "led_panel",
                                        "money_pcb",
                                        "touchscreen",
                                        "speaker"
                                ))
                                .build(),
                        Setting.builder()
                                .id("aae445bf-72f0-4680-a23e-18fcf7241f8b")
                                .requires(Lists.newArrayList())
                                .build(),
                        Setting.builder()
                                .id("76b7f0b8-eb8e-4156-a6cb-43c6b421c69e")
                                .requires(Arrays.asList(
                                        "camera",
                                        "led_matrix"
                                ))
                                .build(),
                        Setting.builder()
                                .id("ae209984-dc64-406b-bc95-3b6153cdbaa6")
                                .requires(Arrays.asList(
                                        "camera",
                                        "pcb",
                                        "led_matrix"
                                ))
                                .build(),
                        Setting.builder()
                                .id("f600ede7-0709-4ca0-b95d-95a5315b9385")
                                .requires(Lists.newArrayList())
                                .build(),
                        Setting.builder()
                                .id("8976a660-f990-46e3-a698-ff8fbb887d46")
                                .requires(Arrays.asList(
                                        "pcb",
                                        "pcb",
                                        "money_receiver",
                                        "touchscreen",
                                        "camera"
                                ))
                                .build(),
                        Setting.builder()
                                .id("922a8e2b-6278-498a-a54a-fd92206ace67")
                                .requires(Lists.newArrayList())
                                .build(),
                        Setting.builder()
                                .id("616e0c31-92ea-4896-8487-62e1b5336aca")
                                .requires(Arrays.asList(
                                        "money_receiver",
                                        "pcb",
                                        "led_panel",
                                        "pcb"
                                ))
                                .build(),
                        Setting.builder()
                                .id("18beae74-a24f-425d-b9d2-8d9d69be89fa")
                                .requires(Lists.newArrayList())
                                .build(),
                        Setting.builder()
                                .id("67ab1ec7-59b8-42f9-b96c-b261cc2a2ed9")
                                .requires(List.of(
                                        "pcb"
                                ))
                                .build(),
                        Setting.builder()
                                .id("2709ac80-2593-4dcf-ae72-a3c2fac023a5")
                                .requires(Arrays.asList(
                                        "pcb",
                                        "money_storage",
                                        "led_matrix",
                                        "speaker",
                                        "pcb"
                                ))
                                .build(),
                        Setting.builder()
                                .id("7e57cfef-7267-4434-b882-a37ac3d76034")
                                .requires(Arrays.asList(
                                        "money_pcb",
                                        "touchscreen",
                                        "money_pcb"
                                ))
                                .build(),
                        Setting.builder()
                                .id("daab00f8-b10e-48f2-bca6-494c5a2869aa")
                                .requires(Arrays.asList(
                                        "touchscreen",
                                        "money_receiver",
                                        "speaker",
                                        "led_panel",
                                        "money_receiver"
                                ))
                                .build(),
                        Setting.builder()
                                .id("a794498e-ce14-499e-8bf6-7d09bda6d3c5")
                                .requires(Arrays.asList(
                                        "money_pcb",
                                        "money_pcb",
                                        "pcb",
                                        "camera"
                                ))
                                .build(),
                        Setting.builder()
                                .id("207797de-5857-4c60-a69b-80eea28bcce8")
                                .requires(List.of(
                                        "pcb"
                                ))
                                .build(),
                        Setting.builder()
                                .id("acbb6362-a6c2-40ce-9ee7-6504816e24d7")
                                .requires(Arrays.asList(
                                        "money_pcb",
                                        "led_matrix",
                                        "amplifier"
                                ))
                                .build(),
                        Setting.builder()
                                .id("358a044e-decc-47cc-aaf1-e2253a00998e")
                                .requires(Lists.newArrayList())
                                .build(),
                        Setting.builder()
                                .id("9ac2d388-0f1b-4137-8415-02b953dd76f7")
                                .requires(Arrays.asList(
                                        "camera",
                                        "money_receiver"
                                ))
                                .build(),
                        Setting.builder()
                                .id("ba4ecdf7-11fa-4d05-8d4b-67b26c991cb0")
                                .requires(Arrays.asList(
                                        "camera",
                                        "led_matrix",
                                        "touchscreen",
                                        "camera"
                                ))
                                .build(),
                        Setting.builder()
                                .id("4efdf86e-68a1-4256-a154-5069510d78fc")
                                .requires(Arrays.asList(
                                        "speaker",
                                        "camera",
                                        "led_panel"
                                ))
                                .build()
                )).build()
        );
        return settingsMono;
    }

    @SneakyThrows
    public Flux<Juke> getJukes() {
        Flux<Juke> jukeFlux = Flux.just(
                Juke.builder()
                        .id("5ca94a8ac470d3e47cd4713c")
                        .model("fusion")
                        .components(Arrays.asList(
                                Component.builder().name("led_panel").build(),
                                Component.builder().name("amplifier").build(),
                                Component.builder().name("led_panel").build(),
                                Component.builder().name("led_panel").build(),
                                Component.builder().name("pcb").build()
                        )).build(),
                Juke.builder()
                        .id("5ca94a8a77e20d15a7d16d0a")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("pcb").build(),
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("touchscreen").build(),
                                        Component.builder().name("speaker").build(),
                                        Component.builder().name("speaker").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a75c231bb18715112")
                        .model("fusion")
                        .components(Arrays.asList(
                                        Component.builder().name("amplifier").build(),
                                        Component.builder().name("led_panel").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a20905ffff6f0561c")
                        .model("virtuo")
                        .components(Arrays.asList(
                                        Component.builder().name("led_panel").build(),
                                        Component.builder().name("money_receiver").build(),
                                        Component.builder().name("money_receiver").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a3227b0a360f41078")
                        .model("fusion")
                        .components(
                                Lists.newArrayList()
                        ).build(),
                Juke.builder()
                        .id("5ca94a8ac3f21c47a72473ec")
                        .model("virtuo")
                        .components(Arrays.asList(
                                        Component.builder().name("led_panel").build(),
                                        Component.builder().name("pcb").build(),
                                        Component.builder().name("amplifier").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8ad82e60f2448d2fc9")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("speaker").build(),
                                        Component.builder().name("touchscreen").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8ab592da6c6f2d562e")
                        .model("fusion")
                        .components(Arrays.asList(
                                        Component.builder().name("camera").build(),
                                        Component.builder().name("amplifier").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8ac5f85b8a59f9e3c8")
                        .model("virtuo")
                        .components(Arrays.asList(
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("camera").build(),
                                        Component.builder().name("camera").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a13385f0c82aa9f2e")
                        .model("virtuo")
                        .components(Arrays.asList(
                                        Component.builder().name("money_storage").build(),
                                        Component.builder().name("pcb").build(),
                                        Component.builder().name("touchscreen").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8aafb9d8c4e4fddf02")
                        .model("angelina")
                        .components(
                                Lists.newArrayList()
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a1639eb9ea30609f0")
                        .model("virtuo")
                        .components(
                                Lists.newArrayList()
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a4aeb7ab33a5e1047")
                        .model("virtuo")
                        .components(Arrays.asList(
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("camera").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8ad2d584257d25ae50")
                        .model("fusion")
                        .components(Arrays.asList(
                                        Component.builder().name("money_receiver").build(),
                                        Component.builder().name("money_receiver").build(),
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("amplifier").build(),
                                        Component.builder().name("led_panel").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a8b58770bb38055a0")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("money_storage").build(),
                                        Component.builder().name("pcb").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8afa2bc9887b28ce87")
                        .model("angelina")
                        .components(List.of(
                                        Component.builder().name("amplifier").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8adb81479f94dda744")
                        .model("fusion")
                        .components(List.of(
                                        Component.builder().name("led_matrix").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a0735998f945f7276")
                        .model("fusion")
                        .components(Arrays.asList(
                                        Component.builder().name("touchscreen").build(),
                                        Component.builder().name("camera").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a59b8061f89644f43")
                        .model("fusion")
                        .components(Arrays.asList(
                                        Component.builder().name("speaker").build(),
                                        Component.builder().name("amplifier").build(),
                                        Component.builder().name("touchscreen").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8acc046e7aa8040605")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("money_receiver").build(),
                                        Component.builder().name("led_matrix").build(),
                                        Component.builder().name("speaker").build(),
                                        Component.builder().name("touchscreen").build(),
                                        Component.builder().name("money_pcb").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8af0853f96c44fa858")
                        .model("virtuo")
                        .components(Arrays.asList(
                                        Component.builder().name("led_matrix").build(),
                                        Component.builder().name("touchscreen").build(),
                                        Component.builder().name("money_storage").build(),
                                        Component.builder().name("pcb").build(),
                                        Component.builder().name("money_receiver").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a18f5576210fd012e")
                        .model("virtuo")
                        .components(
                                Lists.newArrayList()
                        ).build(),
                Juke.builder()
                        .id("5ca94a8ae2b3a4fb2f0cfd78")
                        .model("fusion")
                        .components(Arrays.asList(
                                        Component.builder().name("led_matrix").build(),
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("money_receiver").build(),
                                        Component.builder().name("led_matrix").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8acfdeb5e01e5bdbe8")
                        .model("virtuo")
                        .components(Arrays.asList(
                                        Component.builder().name("money_storage").build(),
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("money_storage").build(),
                                        Component.builder().name("camera").build(),
                                        Component.builder().name("money_receiver").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a2c516506b1f49500")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("led_matrix").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8af9985926172d6e8d")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("speaker").build(),
                                        Component.builder().name("led_matrix").build(),
                                        Component.builder().name("money_pcb").build(),
                                        Component.builder().name("pcb").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a1d1bc6d59afb9392")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("money_storage").build(),
                                        Component.builder().name("speaker").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8aa2330a0762019ac0")
                        .model("angelina")
                        .components(Arrays.asList(
                                        Component.builder().name("money_storage").build(),
                                        Component.builder().name("amplifier").build()
                                )
                        ).build(),
                Juke.builder()
                        .id("5ca94a8ab2c1285e53a89991")
                        .model("fusion")
                        .components(
                                Lists.newArrayList()
                        ).build(),
                Juke.builder()
                        .id("5ca94a8a72473ac501b99033")
                        .model("angelina")
                        .components(
                                Lists.newArrayList()
                        ).build()
        );
        return jukeFlux;
    }
}
